# Generated by Django 4.0 on 2022-05-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('weight', models.FloatField()),
                ('amount', models.FloatField()),
                ('delivery_type', models.CharField(max_length=50)),
            ],
        ),
    ]
