# Generated by Django 4.0 on 2022-06-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='additional_charges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme_name', models.CharField(max_length=100)),
                ('scheme_type', models.IntegerField()),
                ('charge_per_transaction', models.FloatField()),
            ],
        ),
    ]
