# Generated by Django 4.0 on 2022-06-10 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_order_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_details',
        ),
    ]
