# Generated by Django 4.0.5 on 2022-06-19 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0008_delete_order_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='currency_rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=200)),
                ('rate', models.FloatField()),
            ],
        ),
    ]
